name:                ffi-demo
version:             0.1.0.0
github:              "ghulette/ffi-demo"
license:             BSD3
author:              "Geoff Hulette"
maintainer:          "geoff@hulette.net"
copyright:           "Geoff Hulette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ghulette/ffi-demo#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src
  extra-libraries: pcre

tests:
  ffi-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ffi-demo
    - tasty
    - tasty-hunit
